name: CI

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.1' ]

    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Composer caching
        uses: ramsey/composer-install@v2
        with:
          working-directory: ${{ env.wp-plugin-directory }}

      - name: Install dependencies and update PHPUnit
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer install
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run code sniffer
        run: vendor/bin/phpcs --colors
